### ISSUE TITLE
Not sure . . . 'Music' changed the xml construction?

### ISSUE THREAD

**Issue by coziman-vt** [jasmith79/apple_playlist_plex_importer#1]
On MAC OSX Catalina -

Gathering prerequisites...
Connecting...
Retrieving Music Section...
Reading xml file...
Traceback (most recent call last):
  File "/Users/cc/Library/Python/3.7/bin/pleximport", line 10, in <module>
    sys.exit(main())
  File "/Users/cc/Library/Python/3.7/lib/python/site-packages/plex_importer/app.py", line 116, in main
    appl_playlists = extract_apple_playlists(appl_xml)
  File "/Users/cc/Library/Python/3.7/lib/python/site-packages/plex_importer/apple_xml.py", line 34, in extract_apple_playlists
    (playlist["Name"], playlist["Playlist Items"]))
KeyError: 'Playlist Items'

**Comment by jasmith79** [comment]
Your guess is certainly a possibility, Apple is not known for maintaining backwards compatibility.

If the following insults you I apologize in advance but I have no way of knowing what sort of background you have with this sort of thing:

1. Are you sure that you exported the library xml file correctly?
2. Are you sure you passed the path correctly to the script?
3. Can you post your versions of Catalina and Music? e.g. mine are Catalina 10.15.6 and Music 1.0.6.10. You can find these by by clicking the little apple icon in the upper left corner and selecting "About this Mac" and opening the Music app and selecting Music -> About Music.

Thanks!

**Comment by coziman-vt** [comment]
NP - I have a playful programming hobby. ;-) and am an IT admin. 

Exported from other computer (wife’s) so that must be the reason.
Using my workstation to process.
Hmmm
Your comment caused introspection. Logically all should be local.
No joy locally.
Will keep trying.
The library is on a removable. Does that matter? The xml doesn’t show the correct path.
Sigh.


> 
> If the following insults you I apologize in advance but I have no way of knowing what sort of background you have with this sort of thing:
> 
> Are you sure that you exported the library xml file correctly?
> Are you sure you passed the path correctly to the script?
> Can you post your versions of Catalina and Music? e.g. mine are Catalina 10.15.6 and Music 1.0.6.10. You can find these by by clicking the little apple icon in the upper left corner and selecting "About this Mac" and opening the Music app and selecting Music -> About Music.
>

**Comment by jasmith79** [comment]
The actual music path in the xml shouldn't matter, and it shouldn't matter if the file is being processed on a different machine than it was created on. Nor should the path on the Plex Server matter (the script grabs that from each individual track in plex). As long as it's a Library.xml exported from Catalina this should *in theory* work unless they changed the xml structure as you guessed, which is still the best I've heard. If you have some programming skills I recommend firing up the python prompt, importing the script functions from the plex_importer package I created (they should be on PATH already if you installed via pip): `from plex_importer.apple_xml import read_apple_xml` then `result = read_apple_xml("path/to/xml/file")` at that point you can start introspecting on it in the prompt with stuff like `result.keys()` to try to figure out what's missing (it may just be a problem with a subset of your playlists). 

Short of that, email me a copy of your xml at my github username at g-mail and I'll take a look to try to replicate.

**Comment by jasmith79** [comment]
@coziman-vt okay was able to replicate this. Empty playlists don't have a "Playlist Items" key, leading to the KeyError. Re-install, should give you version 0.0.5, which should work. Added bonus, I've now verified it works for xml files created by iTunes (at least on mojave and high sierra) and Windows 10. I added two more flags that might be useful, see --help for details.

**Comment by coziman-vt** [comment]
New error:

Traceback (most recent call last):
  File "/Users/cc/Library/Python/3.7/bin/pleximport", line 5, in <module>
    from plex_importer.app import main
  File "/Users/cc/Library/Python/3.7/lib/python/site-packages/plex_importer/app.py", line 6, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'



Needed to install tqdm.
then


Traceback (most recent call last):
  File "/Users/cc/Library/Python/3.7/bin/pleximport", line 5, in <module>
    from plex_importer.app import main
  File "/Users/cc/Library/Python/3.7/lib/python/site-packages/plex_importer/app.py", line 8, in <module>
    from apple_xml import read_apple_xml, extract_apple_playlists
ModuleNotFoundError: No module named 'apple_xml


No idea what the problem is here.
Sigh.




Installer setup:

cc@MiniMeMac ~ % python3 -m pip install --user git+https://github.com/jasmith79/apple_playlist_plex_importer.git
Collecting git+https://github.com/jasmith79/apple_playlist_plex_importer.git
  Cloning https://github.com/jasmith79/apple_playlist_plex_importer.git to /private/var/folders/t8/dtpkdl6s6nd40cyzzsz2gv5h0000gq/T/pip-req-build-j5_l0uhv
Requirement already satisfied: plexapi in ./Library/Python/3.7/lib/python/site-packages (from plex-importer==0.0.5) (4.1.0)
Requirement already satisfied: requests in ./Library/Python/3.7/lib/python/site-packages (from plexapi->plex-importer==0.0.5) (2.24.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./Library/Python/3.7/lib/python/site-packages (from requests->plexapi->plex-importer==0.0.5) (1.25.10)
Requirement already satisfied: idna<3,>=2.5 in ./Library/Python/3.7/lib/python/site-packages (from requests->plexapi->plex-importer==0.0.5) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in ./Library/Python/3.7/lib/python/site-packages (from requests->plexapi->plex-importer==0.0.5) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./Library/Python/3.7/lib/python/site-packages (from requests->plexapi->plex-importer==0.0.5) (2020.6.20)
Building wheels for collected packages: plex-importer
  Building wheel for plex-importer (setup.py) ... done
  Created wheel for plex-importer: filename=plex_importer-0.0.5-py3-none-any.whl size=8071 sha256=19d7ce517905f7ed56cb78b7d17b6a7ac0655258452103fe10873fae74f3fcc4
  Stored in directory: /private/var/folders/t8/dtpkdl6s6nd40cyzzsz2gv5h0000gq/T/pip-ephem-wheel-cache-jg7gi8d_/wheels/8c/53/c0/57ac67644c09e0bb230958d95db10518df6270eb47eb0cf10e
Successfully built plex-importer
Installing collected packages: plex-importer
Successfully installed plex-importer-0.0.5

**Comment by jasmith79** [comment]
Reinstall (should be 0.0.7 now) and it should work, that was my fault "worked on my machine" should have known better. Thanks again for bearing with me here.

**Comment by coziman-vt** [comment]
You are amazing!

And the latest gets to :

Gathering prerequisites...
Connecting...
Retrieving Music Section...
Reading xml file...
Getting tracks...
Have results, creating list Alfred Publishing - Suzuki Violin School, Volume 1 (Revised) on server:   4%|██▋                                                                       | 7/191 [00:02<01:17,  2.39it/s]
Traceback (most recent call last):
  File "/Users/cc/Library/Python/3.7/bin/pleximport", line 8, in <module>
    sys.exit(main())
  File "/Users/cc/Library/Python/3.7/lib/python/site-packages/plex_importer/app.py", line 121, in main
    plex_server.createPlaylist(list_name, results)
  File "/Users/cc/Library/Python/3.7/lib/python/site-packages/plexapi/server.py", line 280, in createPlaylist
    return Playlist.create(self, title, items=items, limit=limit, section=section, smart=smart, **kwargs)
  File "/Users/cc/Library/Python/3.7/lib/python/site-packages/plexapi/playlist.py", line 177, in create
    return cls._create(server, title, items)
  File "/Users/cc/Library/Python/3.7/lib/python/site-packages/plexapi/playlist.py", line 146, in _create
    uuid = items[0].section().uuid
IndexError: list index out of range

**Comment by jasmith79** [comment]
Okay, that error is unfortunately coming from the plexapi package (i.e. not my code). I've added a try/catch to prevent the whole thing from bailing but it will fail to create those lists, you can see which ones fail if you run with the --debug flag. That's probably the best I can do without debugging their package. I have [opened an issue on their repo](https://github.com/pkkid/python-plexapi/issues/566).

**Comment by jasmith79** [comment]
Workaround with simply not creating the empty lists will have to do for now.
